import type { Metadata } from "next";
import { Inter } from "next/font/google";
import InitialDataLoader from "../components/InitialDataLoader";
import "../styles/globals.scss";
import ReduxProvider from "../utils/redux/StoreProvider";

const inter = Inter({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Kidedvisor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <ReduxProvider>
          {children}
          <InitialDataLoader />
        </ReduxProvider>
      </body>
    </html>
  );
}
