import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import "../styles/globals.scss";
import Header from "../components/Header/Header";

const inter = Inter({ subsets: ["cyrillic"] });
const roboto = Roboto({ subsets: ["cyrillic"], weight: ["400", "500", "700"] });
export const metadata: Metadata = {
  title: "Kidedvisor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${inter.className} ${roboto.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
