# Generated by Django 4.2.3 on 2024-10-07 09:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=150, verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Выберите вид деятельности')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название секции')),
                ('address', models.CharField(db_index=True, max_length=200, verbose_name='Адрес')),
                ('age_s', models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(Decimal('99')), django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Возраст от')),
                ('age_f', models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(Decimal('99')), django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Возраст до')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона для связи')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('tg_contact', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Телеграм')),
                ('whatsapp', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона для связи в whatsapp')),
                ('site', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Сайт')),
                ('time_s', models.TimeField(blank=True, null=True, verbose_name='Время работы с')),
                ('time_f', models.TimeField(blank=True, null=True, verbose_name='Время работы по')),
                ('work_day_mon', models.BooleanField(blank=True, verbose_name='Пн')),
                ('work_day_tue', models.BooleanField(blank=True, verbose_name='Вт')),
                ('work_day_wed', models.BooleanField(blank=True, verbose_name='Ср')),
                ('work_day_thu', models.BooleanField(blank=True, verbose_name='Чт')),
                ('work_day_fri', models.BooleanField(blank=True, verbose_name='Пт')),
                ('work_day_sat', models.BooleanField(blank=True, verbose_name='Сб')),
                ('work_day_sun', models.BooleanField(blank=True, verbose_name='Вс')),
                ('subscription', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Абонементы')),
                ('schedule', models.CharField(blank=True, db_index=True, max_length=1000, verbose_name='Расписание')),
                ('description', models.CharField(blank=True, db_index=True, max_length=1000, verbose_name='Описание')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.category', verbose_name='Выберите направление')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.cities', verbose_name='Выберите город')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/', verbose_name='Фотография')),
                ('order', models.CharField(blank=True, choices=[('Main', 'Главное'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=100, unique=True, verbose_name='Порядок фото')),
                ('section_image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sections.section', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Изображение секции',
                'verbose_name_plural': 'Изображения секций',
            },
        ),
        migrations.AddConstraint(
            model_name='sectionimage',
            constraint=models.UniqueConstraint(fields=('section_image', 'order'), name='unique_image'),
        ),
    ]
