# Generated by Django 4.2.3 on 2024-09-05 14:31

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=150, verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Выберите вид деятельности')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название секции')),
                ('address', models.CharField(db_index=True, max_length=200, verbose_name='Адрес')),
                ('age_s', models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(Decimal('99')), django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Возраст от')),
                ('age_f', models.DecimalField(decimal_places=0, max_digits=2, validators=[django.core.validators.MaxValueValidator(Decimal('99')), django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Возраст до')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Контакты')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('time_s', models.TimeField(blank=True, null=True, verbose_name='Время работы с')),
                ('time_f', models.TimeField(blank=True, null=True, verbose_name='Время работы по')),
                ('days', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Рабочие дни')),
                ('subscription', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Абонементы')),
                ('schedule', models.CharField(blank=True, db_index=True, max_length=1000, verbose_name='Расписание')),
                ('description', models.CharField(blank=True, db_index=True, max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='section_photo/', verbose_name='Фото')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.category', verbose_name='Выберите направление')),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
                'ordering': ('name',),
            },
        ),
    ]
