# Generated by Django 4.2.3 on 2024-08-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='Выберите вид деятельности'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
