# Generated by Django 4.2.3 on 2024-09-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='image',
        ),
    ]
