# Generated by Django 4.2.3 on 2024-08-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='category',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='section',
            name='type',
        ),
    ]
