# Generated by Django 4.2.3 on 2024-08-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_rename_category_section_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='type',
            field=models.CharField(db_index=True, default=1, max_length=200, verbose_name='Выберите вид деятельности'),
            preserve_default=False,
        ),
    ]
