# Generated by Django 4.2.3 on 2024-09-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_remove_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='section_photo/', verbose_name='Фото'),
        ),
    ]
