# Generated by Django 4.2.3 on 2024-08-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_delete_subscription_type_alter_section_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='days',
        ),
        migrations.AddField(
            model_name='section',
            name='days',
            field=models.ManyToManyField(to='sections.days'),
        ),
    ]
