# Generated by Django 4.2.3 on 2024-09-09 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_alter_section_image_sectionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionimage',
            name='section_image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sections.section', verbose_name='Фотографии'),
        ),
    ]
