# Generated by Django 4.2.3 on 2024-08-30 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_remove_section_days_section_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='category_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sections.category', verbose_name='Выберите направление'),
        ),
    ]
