version: '3'

services:
  web:
    env_file: ./backend/env.example
    build:
      context: .
      dockerfile: Dockerfile
    command: /home/worker/backend/run.sh
    volumes:
      - static_volume:/home/worker/staticfiles
    restart: always
    networks:
      - app_network
    expose:
      - 8080
  nginx:
    networks:
      - app_network
    build: ./nginx
    volumes:
      - static_volume:/home/worker/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
networks:
  app_network:
    driver: bridge

volumes:
  static_volume: