version: '3'

services:
  web:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    command: /home/worker/backend/run.sh
    volumes:
      - static_volume:/home/worker/staticfiles
    restart: always
    networks:
      - app_network
    expose:
      - 8080
  nginx:
    networks:
      - app_network
    build: ./nginx
    volumes:
      - static_volume:/home/worker/staticfiles
    ports:
      - 80:80
    depends_on:
      - web
      - frontend
  frontend:
    container_name: "frontend"
    build:
      context: frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    depends_on:
      - web
networks:
  app_network:
    driver: bridge

volumes:
  static_volume: