# Generated by Django 4.2.3 on 2024-08-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('on_queue', 'На очереди'), ('in_moderation', 'На модерации'), ('completed', 'Завершено')], default='on_queue', max_length=100, verbose_name='Статус')),
            ],
        ),
    ]
