# Generated by Django 4.2.3 on 2024-08-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationrequest',
            options={'ordering': ('id',), 'verbose_name': 'Запрос на модерацию', 'verbose_name_plural': 'Запросы на модерацию'},
        ),
    ]
