# Generated by Django 4.2.3 on 2024-08-30 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0002_alter_moderationrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='moderationrequest',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moderationrequest',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
