# Generated by Django 4.2.3 on 2024-08-31 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0003_moderationrequest_created_at_moderationrequest_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationrequest',
            name='response',
            field=models.TextField(default=None, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='moderationrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='moderationrequest',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
