# Generated by Django 4.2.3 on 2024-08-31 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_moderationrequest_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationrequest',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='moderation_requests_owned', to='moderation.moderationrequest'),
        ),
        migrations.AddField(
            model_name='moderationrequest',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.moderationrequest'),
        ),
        migrations.AlterField(
            model_name='moderationrequest',
            name='text',
            field=models.TextField(verbose_name='Запрос'),
        ),
    ]
