# Generated by Django 4.2.3 on 2024-08-31 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0006_alter_moderationrequest_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderationrequest',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='moderationrequest',
            name='parent',
        ),
    ]
