# Generated by Django 4.2.3 on 2024-09-01 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('moderation', '0007_remove_moderationrequest_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationrequest',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='moderation_requests_owned', to='users.rolesuser'),
        ),
        migrations.AddField(
            model_name='moderationrequest',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.rolesuser'),
        ),
    ]
