# Generated by Django 4.2.3 on 2024-09-01 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0008_moderationrequest_owner_moderationrequest_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationrequest',
            options={},
        ),
        migrations.RemoveField(
            model_name='moderationrequest',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='moderationrequest',
            name='parent',
        ),
        migrations.AddField(
            model_name='moderationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='moderationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='moderationrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moderationrequest',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='moderationrequest',
            name='status',
            field=models.CharField(choices=[('queued', 'На очереди'), ('in_moderation', 'На модерации'), ('completed', 'Завершено'), ('response_sent', 'Ответ отправлен')], default='queued', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='moderationrequest',
            name='text',
            field=models.TextField(verbose_name='Текст обращения'),
        ),
        migrations.AlterField(
            model_name='moderationrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
