# Generated by Django 4.2.3 on 2024-09-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0009_alter_moderationrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationrequest',
            options={'ordering': ('id',), 'verbose_name': 'Запрос на модерацию', 'verbose_name_plural': 'Запросы на модерацию'},
        ),
        migrations.AlterField(
            model_name='moderationrequest',
            name='status',
            field=models.CharField(choices=[('queued', 'На очереди'), ('in_moderation', 'На модерации'), ('completed', 'Завершено')], default='queued', max_length=20, verbose_name='Статус'),
        ),
    ]
